

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x240014e1,
     0x2300069d,
     0x0501e1e1,
     0x6f00e1fe,
     0x2400231f,
     0x2a000000,
     0x2402fac0,
     0x24f08080,
     0x0501e0e0,
     0x6f00e0ff,
     0x209d0000 };

