

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRU_test_code[] =  {
     0x240000e0,
     0x240000e1,
     0x240000e2,
     0x240000e3,
     0x240000e4,
     0x240000e5,
     0x240000e6,
     0x240000e7,
     0x240000e8,
     0x240000e9,
     0x240000ea,
     0x240000eb,
     0x240000ec,
     0x240000ed,
     0x240000ee,
     0x240000ef,
     0x240000f0,
     0x240000f1,
     0x240000f2,
     0x240000f3,
     0x240000f4,
     0x240000f5,
     0x240000f6,
     0x240000f7,
     0x240000f8,
     0x240000f9,
     0x240000fa,
     0x240000fb,
     0x240000fc,
     0x240000fd,
     0x240020ff,
     0x2a000000 };

